##
## Makefile for  in /home/planch_j/rendu/CPE/sudoki-bi/bonus/game/
##
## Made by Jean PLANCHER
## Login   <planch_j@epitech.net>
##
## Started on  Sun Feb 28 19:54:47 2016 Jean PLANCHER
## Last update Sun Feb 28 19:59:57 2016 Jean PLANCHER
##

all:
	make -C src

clean:
	make clean -C src

fclean: clean
	make fclean -C src

re: fclean all

.PHONY: all clean fclean re
